reset = "\033[0m"
italic = "\033[3m"
underline = "\033[4m"
strikethrough = "\033[9m"
black = "\033[30m"
red = "\033[31m"
green = "\033[32m"
orange = "\033[38;2;255;153;0m"
yellow = "\033[33m"
blue = "\033[34m"
indigo = "\033[38;2;8;73;158m"
magenta = "\033[35m"
cyan = "\033[36m"
dimWhite = "\033[37m"
blackBackground = "\033[40m"
redBackground = "\033[41m"
greenBackground = "\033[42m"
orangeBackground = "\033[48;2;255;153;0m"
yellowBackground = "\033[43m"
blueBackground = "\033[44m"
indigoBackground = "\033[48;2;8;73;158m"
magentaBackground = "\033[45m"
cyanBackground = "\033[46m"
whiteBackground = "\033[47m"
resetForeground = "\033[39m"
resetBackground = "\033[49m"
ivoryWhite = "\033[1;93m"
pureWhite = "\033[1;97m"
pureWhiteBackground = "\033[37;107m"
if __name__ == "__main__":
	print(f"{italic}Italic "
		  f"{underline}Underline "
		  f"{strikethrough}Strikethrough{reset} Reset")
	print(f"Foreground: {black}B{reset}{red}R{reset}{orange}O{reset}"
		  f"{yellow}Y{reset}{green}G{reset}{blue}U{reset}{indigo}I{reset}"
		  f"{cyan}C{reset}{magenta}M{reset}{dimWhite}W{resetForeground} ResetForeground\n"
		  f"{ivoryWhite}Ivory white{reset} "
		  f"{pureWhite}Pure{reset}")
	print(f"Background: "
		  f"{blackBackground}B{reset}"
		  f"{redBackground}R{reset}"
		  f"{orangeBackground}O{reset}"
		  f"{yellowBackground}Y{reset}"
		  f"{greenBackground}G{reset}"
		  f"{blueBackground}U{reset}"
		  f"{indigoBackground}I{reset}"
		  f"{cyanBackground}C{reset}"
		  f"{magentaBackground}M{reset}"
		  f"{whiteBackground}W{resetBackground} ResetBackground")
	print(f"{pureWhiteBackground}Pure{reset}")
	print(f"Mixing: "
		  f"{red}{whiteBackground}RedForegroundWhiteBackground{reset} "
		  f"{green}{blueBackground}GreenForegroundBlueBackground{reset}")

	print("Mana symbol demo: {X}{X}{X}{4}",
		  blue + "{U}" + reset + red + "{R}" + reset + red + "{R" + reset + "/" + pureWhite + "W}" + reset +
		  pureWhite + "}" + reset)
